# Generated by Django 4.2 on 2023-04-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualprod', '0002_alter_visualprod_number_visualizations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualprod',
            name='rating',
        ),
    ]
