# Generated by Django 4.2 on 2023-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualprod', '0003_remove_visualprod_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualprod',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
